// SPDX-License-Identifier: MIT
package org.simplity.server.core.data;

/**
 * @author simplity.org
 *
 */
public enum FieldType {
	/**
	 * primary key as per RDBMS, that is not internally generated
	 */
	PrimaryKey {
		@Override
		public boolean isUpdated() {
			return false;
		}

		@Override
		public boolean isSetInternally() {
			return false;
		}
	},
	/**
	 * primary key field that is generated by the RDBMS. isRequired() is false for
	 * insert, and true for other cases. This is handled specifically by the code
	 */
	GeneratedPrimaryKey {
		@Override
		public boolean isRequired() {
			return false;
		}

		@Override
		public boolean isUpdated() {
			return false;
		}

		@Override
		public boolean isInserted() {
			return false;
		}
	},
	/**
	 * tenant key is used in a multi-tenant product design.
	 */
	TenantKey {
		@Override
		public boolean isUpdated() {
			return false;
		}

		@Override
		public boolean isRequired() {
			return false;
		}
	},
	/**
	 * id of the user who created this field. (one of the "standard fields")
	 */
	CreatedBy {
		@Override
		public boolean isUpdated() {
			return false;
		}

		@Override
		public boolean isRequired() {
			return false;
		}
	},
	/**
	 * time-stamp at creation. (one of the "standard fields"). This is not set using
	 * a parameter, but using a sql-command
	 */
	CreatedAt {
		@Override
		public boolean isUpdated() {
			return false;
		}

		@Override
		public boolean isRequired() {
			return false;
		}
	},
	/**
	 * id of user who modified this last. (one of the "standard fields")
	 */
	ModifiedBy {
		@Override
		public boolean isRequired() {
			return false;
		}
	},
	/**
	 * time-stamp for last modification. (one of the "standard fields"). This is not
	 * set using a parameter, but using a sql-command
	 */
	ModifiedAt {
		@Override
		public boolean isRequired() {
			return false;
		}
	},
	/**
	 * data column, not key or special field
	 */
	RequiredData {
		@Override
		public boolean isSetInternally() {
			return false;
		}

	},
	/**
	 * data column, not key or special field
	 */
	OptionalData {
		@Override
		public boolean isRequired() {
			return false;
		}

		@Override
		public boolean isSetInternally() {
			return false;
		}
	};

	/**
	 *
	 * @return true if this column is to be included in the SQL for update. For
	 *         example createdUser field should not be updated
	 */
	@SuppressWarnings("static-method")
	public boolean isUpdated() {
		return true;
	}

	/**
	 * @return true if this column is to be included in the SQL for insert. For
	 *         example time-stamp field is not explicitly set in the sql. Also, if
	 *         the primary is generated, then it is not part of the sql statement
	 */
	@SuppressWarnings("static-method")
	public boolean isInserted() {
		return true;
	}

	/**
	 * @return true if value is required from the client. false if it is optional.
	 *         This is used only if isInput() is true. This attribute is not
	 *         applicable if isInput() is false;
	 */
	@SuppressWarnings("static-method")
	public boolean isRequired() {
		return true;
	}

	/**
	 * @return true if this field value is set internally, and user-code should not
	 *         set value to this field
	 */
	@SuppressWarnings("static-method")
	public boolean isSetInternally() {
		return true;
	}
}
